USE master;
IF EXISTS(SELECT * FROM sys.databases WHERE name = 'FlightBookingDB')
BEGIN
ALTER DATABASE FlightBookingDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE FlightBookingDB;
END
GO

CREATE DATABASE FlightBookingDB;
GO

USE FlightBookingDB;
GO

CREATE TABLE [User] (
UserID INT PRIMARY KEY IDENTITY(1,1),
Username VARCHAR(50) NOT NULL,
Password VARCHAR(50) NOT NULL,
FullName NVARCHAR(255) NOT NULL,
Email NVARCHAR(255) NOT NULL,
PhoneNumber NVARCHAR(20) NOT NULL,
Address NVARCHAR(255) NOT NULL,
Role BIT NOT NULL, -- 0 = admin, 1 = user
CONSTRAINT CHK_User_PhoneNumber CHECK (PhoneNumber LIKE '[0-9]%')
);

CREATE TABLE City (
CityID INT PRIMARY KEY IDENTITY(1,1),
CityName NVARCHAR(255) NOT NULL
);

CREATE TABLE Route (
RouteID INT PRIMARY KEY IDENTITY(1,1),
DepartureCityID INT NOT NULL,
ArrivalCityID INT NOT NULL,
Distance INT NOT NULL,
FOREIGN KEY (DepartureCityID) REFERENCES City(CityID),
FOREIGN KEY (ArrivalCityID) REFERENCES City(CityID)
);

CREATE TABLE Flight (
FlightID INT PRIMARY KEY IDENTITY(1,1),
RouteID INT NOT NULL,
DepartureTime DATETIME NOT NULL,
Duration INT NOT NULL,
Capacity INT NOT NULL,
TicketType NVARCHAR(30) NOT NULL,
Price FLOAT NOT NULL,
FOREIGN KEY (RouteID) REFERENCES Route(RouteID),
CONSTRAINT CHK_Flight_Duration CHECK (Duration > 0)
);

CREATE TABLE Booking (
BookingID INT PRIMARY KEY IDENTITY(1,1),
UserID INT NOT NULL,
FlightID INT NOT NULL,
BookingTime DATETIME NOT NULL,
IsPaid BIT NOT NULL, -- 0 = Postpaid(Trả sau), 1 = Paid(Trả trước)
FOREIGN KEY (UserID) REFERENCES [User],
FOREIGN KEY (FlightID) REFERENCES Flight(FlightID)
);

CREATE TABLE PassengerInfo (
PassengerID INT PRIMARY KEY IDENTITY(1,1),
BookingID INT NOT NULL,
FullName NVARCHAR(255) NOT NULL,
Email NVARCHAR(255) NOT NULL,
PhoneNumber NVARCHAR(20) NOT NULL,
Address NVARCHAR(255) NOT NULL,
PassportNumber NVARCHAR(30) NOT NULL,
DateOfBirth DATE NOT NULL,
FOREIGN KEY (BookingID) REFERENCES Booking(BookingID)
);